version: '3.8'

services:
  backend:
    build:
      context: .
      target: backend
    container_name: mnist_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: .
      target: frontend
    container_name: mnist_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000/predict
      - PYTHONUNBUFFERED=1
    depends_on:
      - backend